#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Leonardo.Resource", IsApplication=true)]

namespace Leonardo
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int background = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int blank = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int green_cherry_1 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int green_cherry_2 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int green_cherry_3 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int green_cherry_4 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int green_mushroom_1 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int green_mushroom_2 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int green_mushroom_3 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int green_mushroom_4 = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int green_straw_1 = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int green_straw_2 = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int green_straw_3 = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int green_straw_4 = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int Icon = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int logo = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int monoandroidsplash = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int play = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int play_icon_small = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int red_cherry_1 = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int red_cherry_2 = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int red_cherry_3 = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int red_cherry_4 = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int red_mushroom_1 = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int red_mushroom_2 = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int red_mushroom_3 = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int red_mushroom_4 = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int red_straw_1 = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int red_straw_2 = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int red_straw_3 = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int red_straw_4 = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int x = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int yellow_cherry_1 = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int yellow_cherry_2 = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int yellow_cherry_3 = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int yellow_cherry_4 = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int yellow_mushroom_1 = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int yellow_mushroom_2 = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int yellow_mushroom_3 = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int yellow_mushroom_4 = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int yellow_straw_1 = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int yellow_straw_2 = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int yellow_straw_3 = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int yellow_straw_4 = 2130837547;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f07001c
			public const int absoluteLayout1 = 2131165212;
			
			// aapt resource value: 0x7f07001d
			public const int absoluteLayout2 = 2131165213;
			
			// aapt resource value: 0x7f07001e
			public const int button1 = 2131165214;
			
			// aapt resource value: 0x7f07001f
			public const int button2 = 2131165215;
			
			// aapt resource value: 0x7f070027
			public const int buttonSignIn = 2131165223;
			
			// aapt resource value: 0x7f07002e
			public const int buttonSubmit = 2131165230;
			
			// aapt resource value: 0x7f070028
			public const int editText1 = 2131165224;
			
			// aapt resource value: 0x7f07002b
			public const int editText2 = 2131165227;
			
			// aapt resource value: 0x7f07002d
			public const int editText3 = 2131165229;
			
			// aapt resource value: 0x7f070023
			public const int editTextName = 2131165219;
			
			// aapt resource value: 0x7f070026
			public const int editTextPass = 2131165222;
			
			// aapt resource value: 0x7f070003
			public const int imageButton1 = 2131165187;
			
			// aapt resource value: 0x7f07000e
			public const int imageButton10 = 2131165198;
			
			// aapt resource value: 0x7f07000f
			public const int imageButton11 = 2131165199;
			
			// aapt resource value: 0x7f070010
			public const int imageButton12 = 2131165200;
			
			// aapt resource value: 0x7f070012
			public const int imageButton13 = 2131165202;
			
			// aapt resource value: 0x7f070013
			public const int imageButton14 = 2131165203;
			
			// aapt resource value: 0x7f070014
			public const int imageButton15 = 2131165204;
			
			// aapt resource value: 0x7f070015
			public const int imageButton16 = 2131165205;
			
			// aapt resource value: 0x7f070016
			public const int imageButton17 = 2131165206;
			
			// aapt resource value: 0x7f070019
			public const int imageButton18 = 2131165209;
			
			// aapt resource value: 0x7f07001a
			public const int imageButton19 = 2131165210;
			
			// aapt resource value: 0x7f070004
			public const int imageButton2 = 2131165188;
			
			// aapt resource value: 0x7f070018
			public const int imageButton20 = 2131165208;
			
			// aapt resource value: 0x7f070005
			public const int imageButton3 = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int imageButton4 = 2131165190;
			
			// aapt resource value: 0x7f070008
			public const int imageButton5 = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int imageButton6 = 2131165193;
			
			// aapt resource value: 0x7f07000a
			public const int imageButton7 = 2131165194;
			
			// aapt resource value: 0x7f07000b
			public const int imageButton8 = 2131165195;
			
			// aapt resource value: 0x7f07000d
			public const int imageButton9 = 2131165197;
			
			// aapt resource value: 0x7f07001b
			public const int imageView1 = 2131165211;
			
			// aapt resource value: 0x7f070021
			public const int linearLayout1 = 2131165217;
			
			// aapt resource value: 0x7f070029
			public const int linearLayout2 = 2131165225;
			
			// aapt resource value: 0x7f070024
			public const int linearLayout3 = 2131165220;
			
			// aapt resource value: 0x7f070001
			public const int tableLayout1 = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int tableRow1 = 2131165186;
			
			// aapt resource value: 0x7f070007
			public const int tableRow2 = 2131165191;
			
			// aapt resource value: 0x7f07000c
			public const int tableRow3 = 2131165196;
			
			// aapt resource value: 0x7f070011
			public const int tableRow4 = 2131165201;
			
			// aapt resource value: 0x7f070000
			public const int textView1 = 2131165184;
			
			// aapt resource value: 0x7f070017
			public const int textView3 = 2131165207;
			
			// aapt resource value: 0x7f07002a
			public const int textView4 = 2131165226;
			
			// aapt resource value: 0x7f07002c
			public const int textView5 = 2131165228;
			
			// aapt resource value: 0x7f070022
			public const int textViewName = 2131165218;
			
			// aapt resource value: 0x7f070025
			public const int textViewPass = 2131165221;
			
			// aapt resource value: 0x7f070020
			public const int textViewSignIn = 2131165216;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Game = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int SignIn = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int SignUp = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int clickInMenu = 2130968576;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int Mono_Android_Theme_Splash = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
