#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Leonardo.Resource", IsApplication=true)]

namespace Leonardo
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int background = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int blank = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int green_cherry_1 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int green_cherry_2 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int green_cherry_3 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int green_cherry_4 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int green_mushroom_1 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int green_mushroom_2 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int green_mushroom_3 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int green_mushroom_4 = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int green_straw_1 = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int green_straw_2 = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int green_straw_3 = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int green_straw_4 = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int Icon = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int logo = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int play = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int play_icon_small = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int red_cherry_1 = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int red_cherry_2 = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int red_cherry_3 = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int red_cherry_4 = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int red_mushroom_1 = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int red_mushroom_2 = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int red_mushroom_3 = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int red_mushroom_4 = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int red_straw_1 = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int red_straw_2 = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int red_straw_3 = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int red_straw_4 = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int x = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int yellow_cherry_1 = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int yellow_cherry_2 = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int yellow_cherry_3 = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int yellow_cherry_4 = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int yellow_mushroom_1 = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int yellow_mushroom_2 = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int yellow_mushroom_3 = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int yellow_mushroom_4 = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int yellow_straw_1 = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int yellow_straw_2 = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int yellow_straw_3 = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int yellow_straw_4 = 2130837546;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f06001c
			public const int button1 = 2131099676;
			
			// aapt resource value: 0x7f06001d
			public const int button2 = 2131099677;
			
			// aapt resource value: 0x7f060003
			public const int imageButton1 = 2131099651;
			
			// aapt resource value: 0x7f06000e
			public const int imageButton10 = 2131099662;
			
			// aapt resource value: 0x7f06000f
			public const int imageButton11 = 2131099663;
			
			// aapt resource value: 0x7f060010
			public const int imageButton12 = 2131099664;
			
			// aapt resource value: 0x7f060012
			public const int imageButton13 = 2131099666;
			
			// aapt resource value: 0x7f060013
			public const int imageButton14 = 2131099667;
			
			// aapt resource value: 0x7f060014
			public const int imageButton15 = 2131099668;
			
			// aapt resource value: 0x7f060015
			public const int imageButton16 = 2131099669;
			
			// aapt resource value: 0x7f060016
			public const int imageButton17 = 2131099670;
			
			// aapt resource value: 0x7f060019
			public const int imageButton18 = 2131099673;
			
			// aapt resource value: 0x7f06001a
			public const int imageButton19 = 2131099674;
			
			// aapt resource value: 0x7f060004
			public const int imageButton2 = 2131099652;
			
			// aapt resource value: 0x7f060018
			public const int imageButton20 = 2131099672;
			
			// aapt resource value: 0x7f060005
			public const int imageButton3 = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int imageButton4 = 2131099654;
			
			// aapt resource value: 0x7f060008
			public const int imageButton5 = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int imageButton6 = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int imageButton7 = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int imageButton8 = 2131099659;
			
			// aapt resource value: 0x7f06000d
			public const int imageButton9 = 2131099661;
			
			// aapt resource value: 0x7f06001b
			public const int imageView1 = 2131099675;
			
			// aapt resource value: 0x7f060001
			public const int tableLayout1 = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int tableRow1 = 2131099650;
			
			// aapt resource value: 0x7f060007
			public const int tableRow2 = 2131099655;
			
			// aapt resource value: 0x7f06000c
			public const int tableRow3 = 2131099660;
			
			// aapt resource value: 0x7f060011
			public const int tableRow4 = 2131099665;
			
			// aapt resource value: 0x7f060000
			public const int textView1 = 2131099648;
			
			// aapt resource value: 0x7f060017
			public const int textView3 = 2131099671;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Game = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int SignIn = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int SignUp = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int clickInMenu = 2130968576;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
